trigger:
- master

pool:
  vmImage: 'macOS-latest'

variables:
  GOBIN:  '$(GOPATH)/bin' # Go binaries path
  GOROOT: '/usr/local/go1.11' # Go installation path
  GOPATH: '$(system.defaultWorkingDirectory)/gopath' # Go workspace path
  modulePath: '$(GOPATH)/src/github.com/$(build.repository.name)' # Path to the module's code

steps:
- script: |
    echo '--------------- which go ----------'
    which go
    echo '-----------------------------------'
    mkdir -p '$(GOBIN)'
    mkdir -p '$(GOPATH)/pkg'
    mkdir -p '$(modulePath)'
    shopt -s extglob
    mv !(gopath) '$(modulePath)'
    echo '##vso[task.prependpath]$(GOBIN)'
    echo '##vso[task.prependpath]$(GOROOT)/bin'
    echo 'GOBIN=$(GOBIN)'
    echo 'GOROOT=$(GOROOT)'
    echo 'GOPATH=$(GOPATH)'
    echo 'modulePath=$(modulePath)'
    find '$(modulePath)'
  displayName: 'Set up the Go workspace'


- task: Bash@3
  displayName: 'Run tests'
  inputs:
    targetType: 'inline'
    workingDirectory: '$(modulePath)'
    script: |
      pwd
      find '$(modulePath)'
      go get -v -u github.com/jstemmer/go-junit-report
      find '$(modulePath)'
      go test -v 2>&1 | go-junit-report > test-results.xml

- task: PublishTestResults@2
  inputs:
    testResultsFormat: 'JUnit'
    testResultsFiles: 'test-results.xml'

- task: Bash@3
  displayName: 'Build the plugin'
  inputs:
    targetType: 'inline'
    script: |
      make all




