trigger:
- master

pool:
  vmImage: 'macOS-latest'

steps:
- task: Bash@3
  displayName: 'Install dependencies'
  inputs:
    targetType: 'inline'
    script: |
      go get -u github.com/jstemmer/go-junit-report


- task: Bash@3
  displayName: 'Run tests'
  inputs:
    targetType: 'inline'
    script: |
      go test -v 2>&1 | go-junit-report > test-results.xml

- task: PublishTestResults@2
  inputs:
    testResultsFormat: 'JUnit'
    testResultsFiles: 'test-results.xml'

- task: Bash@3
  displayName: 'Build the plugin'
  inputs:
    targetType: 'inline'
    script: |
      make all




